site_name: Binance Chain Docs
site_description: Binance Chain Technology Documentation
site_author: Binance Chain Community

repo_url: https://github.com/binance-chain/
edit_uri: ""
use_directory_urls: false

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - go
    - java
    - javascript

nav:
  - Home: index.md
  - API Reference:
    - HTTP API - Paths and Models: api-reference/dex-api/paths.md
    - WebSockets - Connecting: api-reference/dex-api/ws-connection.md
    - WebSockets - Streams: api-reference/dex-api/ws-streams.md
    - Node RPC: api-reference/node-rpc.md
    - SDK: api-reference/sdk.md
    - Commands: api-reference/cli.md
    - Transactions: encoding.md
  - More Help: resources.md
  - Binance DEX TestNet: https://testnet.binance.org
  - Chain Explorer TestNet: https://testnet-explorer.binance.org

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list

plugins:
  - search:
      prebuild_index: true
