site_name: Binance Chain Docs
site_description: Binance Chain Technology Documentation
site_author: Binance Chain Community

repo_url: https://github.com/binance-chain/
edit_uri: ""
use_directory_urls: false

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - go
    - java
    - javascript

nav:
  - Home: index.md
  - API Reference:
    - HTTP API - Paths and Models: api-reference/dex-api/paths.md
    - WebSockets - Connecting: api-reference/dex-api/ws-connection.md
    - WebSockets - Streams: api-reference/dex-api/ws-streams.md
    - Node RPC: api-reference/node-rpc.md
    - API Server: api-reference/api-server.md
    - Light Client: light-client.md
    - SDK: api-reference/sdk.md
    - Commands: api-reference/cli.md
    - Transactions: encoding.md
    - WalletConnect: walletconnect.md
    - Changelog: changelog.md
  - FAQ: faq.md
  - Exchange Integration: exchange-integration.md
  - RPC Swagger: rpc-swagger/index.html
  - API Swagger: api-swagger/index.html
  - List Instructions: list_instruction.md
  - Wallets: wallets.md
  - Tutorials: tutorials.md
  - More Help: resources.md
  - Binance DEX TestNet: https://testnet.binance.org
  - Chain Explorer TestNet: https://testnet-explorer.binance.org
  - Get Testnet Funds: https://www.binance.vision/tutorials/binance-dex-funding-your-testnet-account

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list

plugins:
  - search:
      prebuild_index: true
