site_name: Binance Chain Docs
site_description: Binance Chain Technology Documentation
site_author: Binance Chain Community

repo_url: https://github.com/binance-chain/
edit_uri: ""
use_directory_urls: false

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'yellow'
    accent: 'grey'
  logo:
    icon: 'build'
  feature:
    tabs: true
extra_css:
       - stylesheets/dark_theme.css
       - stylesheets/codehilite.css
nav:
  - Home: index.md
  - Binance Chain:
    - Introduction: guides/intro.md
    - Create Address: guides/create-address.md
    - Binance DEX Trading: guides/trading-interface.md
    - Chain Explorer Mainnet: https://explorer.binance.org
    - Binance Chain Testnet: guides/testnet.md
    - Chain Explorer Testnet: https://testnet-explorer.binance.org
    -  Concepts:
       - Blockchain Concepts:
          - Architecture: guides/concepts/architecture.md
          - Accounts: guides/concepts/accounts.md
          - Assets: guides/concepts/assets.md
          - Transaction: guides/concepts/transaction.md
          - Genesis File: guides/concepts/genesis.md
          - Signature: guides/concepts/signature.md
          - Encoding:
            - Encoding: guides/concepts/encoding/encoding.md
            - Amino Encoding: guides/concepts/encoding/amino-example.md
       - Binance Chain and DEX:
         - Fees: guides/concepts/fees.md
         - Binance Chain Governance: governance.md
         - Binance DEX Match Engine Design:
           - Trading Spec: trading-spec.md
           - Match Engine: match.md
           - Match examples: match-examples.md
         - Binance Chain Evolution Proposal: https://github.com/binance-chain/BEPs/blob/master/BEP1.md
         - Threshold Signature Scheme: guides/concepts/threshold-signature-scheme.md
         - Atomic Swap: atomic-swap.md
         - WalletConnect: guides/concepts/walletconnect.md
  - Binance Smart Chain:
    - Introduction: smart-chain/guides/bsc-intro.md
    - Concepts:
      - Consensus: smart-chain/guides/concepts/consensus.md
      - Comparison: smart-chain/guides/general.md
      - Genesis File: smart-chain/guides/concepts/genesis.md
      - Participate: smart-chain/developer/fullnode.md
      - Cross-chain:
        - Cross-chain Mechanism: smart-chain/guides/concepts/cross-chain.md
        - BSC Relayer: smart-chain/guides/concepts/bsc-relayer.md
        - Oracle Module: smart-chain/guides/concepts/oracle-module.md
        - Oracle Relayer: smart-chain/guides/concepts/oracle-relayer.md
        - Relayer Incentives: smart-chain/guides/concepts/incentives.md
    - Staking:
      - Validator:
        - Guides: smart-chain/validator/guideline.md
        - Become Candidate: smart-chain/validator/candidate.md
        - Staking parameters: smart-chain/validator/Parameters.md
      - Delegator Guide: smart-chain/delegator/del-guide.md
    - Binance Smart Chain Explorer: https://explorer.binance.org/smart-testnet
    - Wallet:
      - MetaMask Guides: smart-chain/wallet/metamask.md
      - Ledger: smart-chain/wallet/ledger.md
      - MEW: smart-chain/wallet/myetherwallet.md
  - Developers:
    - Binance Chain Fullnode:
      - Install: guides/node/install.md
      - Join Mainnet: guides/node/join-mainnet.md
      - Join Testnet: guides/node/join-testnet.md
      - Diffferet Syncing Modes: guides/node/synctypes.md
      - Get Extra Details from Your Fullnode: guides/node/extra-info.md
      - Different Fullnodes in network: guides/node/nodetypes.md
      - Upgrade: guides/node/upgrade.md
      - Local Network: guides/node/localnetwork.md
      - Common Issues: fullnodeissue.md
    - Binance Chain Client: api-reference/cli.md
    - Light Client: light-client.md
    - Simple API Server: api-reference/api-server.md
    - Binance Chain SDK:
      - GoLang: https://github.com/binance-chain/go-sdk/wiki
      - JavaScript: https://github.com/binance-chain/javascript-sdk/wiki
      - Python: https://github.com/binance-chain/python-sdk
      - Java: https://github.com/binance-chain/java-sdk/wiki
      - Swift: https://github.com/binance-chain/swift-sdk/blob/master/README.md
      - C++: https://github.com/binance-chain/cplusplus-sdk/wiki
      - C#: https://github.com/binance-chain/csharp-sdk
    - Binance Chain API Reference:
      - Accelerated Node HTTP API - Paths and Models: api-reference/dex-api/paths.md
      - Accelerated Node HTTP API Swagger: api-swagger/index.html
      - WebSockets - Connecting: api-reference/dex-api/ws-connection.md
      - WebSockets - Streams: api-reference/dex-api/ws-streams.md
      - Node RPC - Paths and Models: api-reference/node-rpc.md
      - Node RPC Swagger: rpc-swagger/index.html
      - CHANGELOG: changelog.md
    - Binance Smart Chain:
      - Binance Smart Chain Fullnode: smart-chain/developer/fullnode.md
      - BSC Relayer: smart-chain/developer/bsc-relayer.md
      - BEP2E Tokens: smart-chain/developer/BEP2E.md
      - General:
        - Create Wallet: smart-chain/developer/create-wallet.md
        - BEP2E:
          - Issue Token: smart-chain/developer/issue-BEP2E.md
          - Bind Token: smart-chain/developer/bind-tokens.md
          - Cross-chain Transfer: smart-chain/validator/cross-chain-transfer.md
      - RPC: smart-chain/developer/rpc.md
  - Wallets:
    - Binance Chain Walletsupport: wallets/wallets.md
    - Wallet Tutorial:
      - Trust Wallet User Guide: wallets/tutorial/how-to-create-a-wallet-on-trustwallet.md
      - Ledger Wallet Guide: wallets/tutorial/ledger-nano-s-usage-guide.md
      - Trezor Wallet Guide: wallets/tutorial/trezor-model-t-user-guide.md
    - WalletConnectSupport: wallets/walletconnect-support.md
  - Exchange Integration: exchange-integration.md
  - List Instructions: list_instruction.md
  - Wallets: wallets.md
  - Binance Smart Chain White Paper: https://github.com/binance-chain/whitepaper/blob/master/WHITEPAPER.md
  - Chain Explorer Mainnet: https://explorer.binance.org
  - Binance Chain Forum: https://community.binance.org/
  - Binance DEX Testnet: https://testnet.binance.org
  - Chain Explorer Testnet: https://testnet-explorer.binance.org
  - Get Testnet Funds: https://www.binance.vision/tutorials/binance-dex-funding-your-testnet-account
  - Binance Smart Chain Testnet Explorer: https://explorer.binance.org/smart-testnet
  - Binance Smart Chain Faucet: https://testnet.binance.org/faucet-smart
  - The Binance Chain Telegram Group : https://t.me/BinanceDEXchange
  - Twitter: https://twitter.com/binance_dex
  - Telegram Announcement Channel English: https://t.me/Binance_DEX_Announcement
  - 币安DEX中文群: https://t.me/BinanceDEXchangeCN
  - 币安链公告频道: https://t.me/Binance_DEX_ChineseAnnouncements
  - FAQ:
    - Binance Chain FAQ: faq/faq.md
    - Binance Smart Chain FAQ:
      - General:
        - Info: faq/bsc/general.md
        - Binance Smart Chain: faq/bsc/bsc.md
        - Ecosystem: faq/bsc/eco.md
      - Token:
        - Intro: faq/bsc/token.md
        - BEPs: faq/bsc/bep.md
      - Staking:
        - Validator: faq/bsc/val.md
        - Delegator: faq/bsc/del.md
      - Crosschain: faq/bsc/cross.md
  - More Help: resources.md
  - Contributing: CONTRIBUTING.md


markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.superfences
    - codehilite



plugins:
  - search

repo_name: 'binance-chain/docs-site'
repo_url: 'https://github.com/binance-chain/docs-site'

extra:
  social:
    - type: 'github'
      link: 'binance-chain/docs-site'
    - type: 'twitter'
      link: 'https://twitter.com/Binance_DEX'
    - type: 'website'
      link: 'https://www.binance.org'